### ISSUE TITLE
Internal server error trying to save opencollective username

### ISSUE THREAD

**Issue by ccatterina** [getmoto/payments#4]
Hi!
When I try to save the opencollective username on moto payments web app, the backend replies with an Internal server error:

![image](https://github.com/getmoto/payments/assets/9085116/6043ac08-2ece-44f0-bf75-24463fe2233a)

I have tried to figure out the reason for the error by looking at the code, but I can't find anything.

**Comment by bblommers** [comment]
Thanks for letting us know @ccatterina - I'll have a look!

**Comment by bblommers** [comment]
Can you try again @ccatterina? I've pushed #5 to prod, and I can't reproduce it anymore

**Comment by ccatterina** [comment]
Now it works! ty
